### ISSUE TITLE
Selection bug

### ISSUE THREAD

**Issue by tmarble** [dollabs/planviz#35]
@pmdoll writes:
> I am able to reproduce the bug. When the bug is active, selection of HTN
> node causes correct behavior in TPN view but not in HTN view. i.e the
> clicked HTN node is not selected. selection of TPN node or edge causes the
> corresponding HTN node to be selected as expected.

For me it's clicking on the HTN does not update the TPN view.. Initially.
Clicking on the TPN does update the HTN view. Then HTN->TPN selection works.

Will investigate.

**Comment by dcerys** [comment]
It seems this is an intermittent bug, that can cause selection failure in both directions.   The problem I saw: selecting TPN activities properly updated the HTN node with selection, but didn't cause the selected TPN activity to be marked with selection.  After a period of time (a few minutes, doing something else), TPN and HTN selection both worked properly again.

**Comment by pmdoll** [comment]
Opening this issue until we verify that it address all previously known nits.

**Comment by pmdoll** [comment]
Could not reproduce this issue in revision 77b24e9ac263f68a750b57a2870b5eea5dca9124.
