### ISSUE TITLE
planviz does not render tpn-between correctly

### ISSUE THREAD

**Issue by pmdoll** [dollabs/planviz#48]
Generate htn and tpn files and load them in planviz. Nothing shows up

### Generate TPN only

```
pamela -i tpn-between.pamela -f json -o tpn-between.2.tpn.json tpn
```

### Generate HTN and TPN

```
pamela -i tpn-between.pamela -o tpn-between -t "(tpn.elephant)" htn
```

**Comment by tmarble** [comment]
Currently planviz does render `tpn-between.2.tpn.json` correctly.

The second example does not count because the `elephant` method is not a valid HTN method.

Closing.

**Comment by pmdoll** [comment]
We need a variant of the elephant for testing with HTN and TPN generation. Could you create one? Bonus if we could reuse the methods in both original and htn variant.
